### ISSUE TITLE
Snippets for VS

### ISSUE THREAD

**Issue by agust220** [AdrianWilczynski/.NETCoreSnippetPack#4]
Is there or will there be a **Visual Studio** version?
Or is there perhaps a way to port them over, `JSON` to `.snippet` files?

**Comment by AdrianWilczynski** [comment]
Here you go: https://github.com/AdrianWilczynski/.NETCoreSnippetPack/tree/master/for%20Visual%20Studio%202019

I've started writing VSCode to Visual Studio snippet converter like a year ago, but I've never finished it properly. These should mostly work, but there are no guarantees or support ^^

**Comment by agust220** [comment]
> Here you go: https://github.com/AdrianWilczynski/.NETCoreSnippetPack/tree/master/for%20Visual%20Studio%202019
> 
> I've started writing VSCode to Visual Studio snippet converter like a year ago, but I've never finished it properly. These should mostly work, but there are no guarantees or support ^^

Sweet! Thank you 👌
